[[redirects]]
  from = "/meetups"
  to = "/events"
  status = 301

[[redirects]]
  from = "/londonfeedback"
  to = "https://www.surveymonkey.co.uk/r/WVLNHGN"
  status = 302

[[redirects]]
  from = "/londonvideos"
  to = "https://www.youtube.com/channel/UCcY68Rc35-UXADMXOH8G7eA"
  status = 302

[[redirects]]
  from = "/live"
  to = "https://2021.demuxed.com/live"
  status = 302
